import './globals.css'
import {Inter} from 'next/font/google'
import Navbar from "@/components/navbar";
import {Web3Provider} from "@/app/web3/web3Connectors";
import Providers from "@/app/utils/queryProvider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            <Web3Provider>
                <Navbar/>
                {children}
            </Web3Provider>
        </Providers>
        </body>
        </html>
    )
}
